version: '3'

services:
  db:
    container_name: foodgram_db
    image: postgres:13
    restart: always
    env_file: .env
    volumes:
      - pg_fdata:/var/lib/postgresql/data

  backend:
    container_name: foodgram_backend
    image: fyuriko/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
      - data:/app/data
    depends_on:
      - db

  frontend:
    container_name: foodgram_front
    image: fyuriko/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/ 
    volumes:
      - static:/frontend_static 

  nginx:
    container_name: foodgram_proxy
    image: fyuriko/foodgram_proxy
    ports:
      - 9000:80
    volumes:
      - static:/staticfiles/
      - media:/media
    depends_on:
      - backend
      - frontend

volumes:
  pg_fdata:
  static:
  media:
  data:
...
