# Generated by Django 4.2.5 on 2023-10-10 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="recipe", unique_together={("name", "text")},
        ),
    ]
