# Generated by Django 3.2.3 on 2023-10-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230930_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientinrecipe',
            old_name='quantity',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=254, verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=254, verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=254, unique=True, verbose_name='Тэг'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=254, unique=True, verbose_name='Слаг'),
        ),
    ]
