# Generated by Django 4.2.5 on 2023-10-10 11:58

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_recipe_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="recipes",
                through="recipes.IngredientInRecipe",
                to="recipes.ingredient",
                verbose_name="Ингредиенты",
            ),
        ),
    ]
