# Generated by Django 4.2.5 on 2023-10-11 16:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0004_alter_recipe_ingredients"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="favorite", unique_together={("user", "recipe")},
        ),
        migrations.AlterUniqueTogether(
            name="shoppingcart", unique_together={("user", "recipe")},
        ),
    ]
