# Generated by Django 3.2.3 on 2023-10-02 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20231002_1213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagInRecipe',
        ),
    ]
