# Generated by Django 4.2.5 on 2023-10-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_alter_favorite_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(max_length=7, unique=True, verbose_name="Цвет"),
        ),
    ]
