# Generated by Django 4.2.5 on 2023-10-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_alter_tag_color"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ingredientinrecipe",
            constraint=models.UniqueConstraint(
                fields=("recipe", "ingredient"), name="unique_ingredient_in_recipe"
            ),
        ),
    ]
