# Generated by Django 4.2.5 on 2023-10-12 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0008_ingredientinrecipe_unique_ingredient_in_recipe"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ingredientinrecipe", name="unique_ingredient_in_recipe",
        ),
        migrations.AlterUniqueTogether(
            name="ingredientinrecipe", unique_together={("recipe", "ingredient")},
        ),
    ]
