# Generated by Django 4.2.5 on 2023-10-10 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="follow",
            options={"verbose_name": "Подписка", "verbose_name_plural": "Подписки"},
        ),
    ]
